name: publish image

on: [ push ]

jobs:
  publish-image:
    runs-on: ubuntu-latest
    env: 
      IMAGE_NAME:  ghcr.io/avinal/lark:${{ secrets.VERSION }}

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build the lark Docker image
        run: docker build . --tag $IMAGE_NAME

      - name: Push lark to GitHub Container Registry
        run: docker push $IMAGE_NAME
